<?php

namespace Marie\LouvresBundle\Repository;

/**
 * ticketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class countryRepository extends \Doctrine\ORM\EntityRepository
{
}
